version: "3.9"

services:
  app:
    build: .
    container_name: pokehelp-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:password@db:3306/pokehelp
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pokehelp
    ports:
      - "3307:3306"
    networks:
      - app-net
    volumes:
      - mysql-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app-net

volumes:
  mysql-data:
  grafana-data:

networks:
  app-net:
