version: '3.8'

services:
  app:
    build: .
    container_name: pokehelp-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://pokeuser:password@mysql:3306/pokehelp
      - NODE_ENV=production
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: pokehelp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokehelp
      MYSQL_USER: pokeuser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pokehelp-pma
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data:
